<?php

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @author Andrew S Erwin
 * @link https://andrewthecoder.com
 **/

/**
 * @param int $range how far to check?
 * @return int 
 */
function sum(int $range): int {
    $a = 1;
    $b = 2;
    $c = 0;
    $sum = 0;

    do {
        if ($c % 2 == 0) {
            $sum += $c;
        }
        
        $c = $a + $b;
        $a = $b;
        $b = $c;
    } while ($c <= $range); 

    return $sum;
}

print sum(4000000);
